### ISSUE TITLE
python2.7 manage.py runserver  --- error

### ISSUE THREAD

**Issue by chesterwang** [namco1992/job_analysis#1]
(11:37:38 on master)──> bash run_test                                        ──(六, 7月09)─┘
/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.
    .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.moment is deprecated, use flask_moment instead.
    .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.assets is deprecated, use flask_assets instead.
    .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
    .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
    File "manage.py", line 3, in <module>
        from app import create_app
    File "/home/chester/github.com/job_analysis/app/**init**.py", line 11, in <module>
        from config import config
ImportError: cannot import name config

**Comment by namco1992** [comment]
出于安全考虑，我没有把 config 放上去，我会把 config 的示例文件传上来

**Comment by chesterwang** [comment]
本地测试的config也可以啊，你run_test,可以用测试的版本啊

**Comment by namco1992** [comment]
已上传 config.py 文件，请重新 pull 一下。
